a="fuck you donald trump"
print(len(a))
print(a[0:19])
print(a[0:10:2])
print(a[0::2])
print(a[-8:-5])
print(a[::-1])
print(a.isalnum())
print(a.isalpha())
print(a.endswith("mp"))
print(a.count("o"))
print(a.capitalize())
print(a.find("yo"))
print(a.lower())
print(a.upper())
print(a.replace("fuck you","asshole"))